// Mocks generated by Mockito 5.3.2 from annotations
// in burger/test/data/repositories/burger_repository_imp_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:burger/data/services/burgers/burger_service.dart' as _i2;
import 'package:burger/domain/entities/burger.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [BurgerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBurgerService extends _i1.Mock implements _i2.BurgerService {
  MockBurgerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Burger>> findBurgers() => (super.noSuchMethod(
        Invocation.method(
          #findBurgers,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Burger>>.value(<_i4.Burger>[]),
      ) as _i3.Future<List<_i4.Burger>>);
}
