///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String assets = 'assets/.env_develop';
  static const String burgerAssets = 'assets/.env_production';
  static const String imagesAndalouse = 'assets/images/andalouse.png';
  static const String imagesBurger1 = 'assets/images/burger_1.png';
  static const String imagesBurger2 = 'assets/images/burger_2.png';
  static const String imagesEllipse = 'assets/images/ellipse.png';
  static const String imagesHarissa = 'assets/images/harissa.png';
  static const String imagesKetchup = 'assets/images/ketchup.png';
  static const String imagesLoading = 'assets/images/loading.gif';
  static const String imagesSauceBlanche = 'assets/images/sauce-blanche.png';
  static const String imagesSaucePoivre = 'assets/images/sauce-poivre.png';
  static const String imagesStar = 'assets/images/star.png';
  static const String imagesUser = 'assets/images/user.png';
  static const String jsonCart = 'assets/json/cart.json';
  static const String jsonLoading = 'assets/json/loading.json';
  static const String jsonServerError = 'assets/json/server-error.json';
  static const String jsonStar = 'assets/json/star.json';
  static const String translationsEn = 'assets/translations/en.json';
  static const String translationsFr = 'assets/translations/fr.json';
}
